/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package condominio.device.rfid.test;

import com.diozero.api.DigitalOutputDevice;
import com.diozero.devices.MFRC522;

public class App {
    MFRC522 mfrc = new MFRC522(24,22);
    public String getGreeting() {
        return "DIO Project - MFRC522 Teste";
    }

    public void execute() {
        System.out.println("Aguardando cartão para leitura ...");
        MFRC522.UID uid = mfrc.readCardSerial();
        String texto = new String(uid.getUidBytes());
        System.out.println("Bytes Lidos ==>" + texto);
    }

    public static void main(String[] args) {
        App app = new App();
        System.out.println(app.getGreeting());
        app.execute();
        System.out.println("Concluido");
    }
}
